### ISSUE TITLE
The action workflow Cron don't work.

### ISSUE THREAD

**Issue by berlin4apk** [mcb30/firmware-tester#1]
The Cron workflow creating and pushing the docker Image don't work, as the last workflow run was 8 months ago

**Comment by mcb30** [comment]
Thanks.  The workflow had been automatically disabled after 60 days of repository inactivity.  I've re-enabled the scheduled workflow and also added the ability for the workflow to be triggered manually.

**Comment by berlin4apk** [comment]
Thanks for the quick fix.
